### ISSUE TITLE
Transition page

### ISSUE THREAD

**Issue by leonardloo** [opengovsg/GoGovSG#10]
**Describe feature request**
A few reasons why a transition page would be helpful:
1. **Anti phishing:** Citizens should land on a page to verify go.gov.sg before being led off to long link. Phishers can easily place go.gov.sg in front of their QR codes pointing to malicious domains. 
2. **User experience**: Users can anticipate if the long link is something they want to visit before actually visiting

**Describe the solution you'd like**
1. Serve transition page once a user visits any go.gov.sg link.
2. Button click to move past the page
3. If button not clicked, transition page lasts for 5 seconds (To be confirmed by designers if this should be removed because it can be destabilising)
4. Transition page should still serve meta tag information on destination page on social media

In the future, there can be another issue to customise message that appears on the transition page.

Sample screenshot:
![image](https://user-images.githubusercontent.com/4787315/80673677-75b10980-8ae2-11ea-917e-a6ef7bbdfc5e.png)

**Comment by liangyuanruo** [comment]
> Sample screenshot:

Lose the "proceed" button? The transition should be automatic.

**Comment by liangyuanruo** [comment]
### Proposed approach

1. Use a library to detect crawlers and parse the user agent string. If a crawler is detected, we always redirect immediately so meta tags will always work and we don’t have to do any of the parsing/caching ourselves. Crawler user agent strings ought to be fairly obvious and so it should be possible to do this reliably.

2. To avoid delaying the user repeatedly by serving the transition page, we can set a cookie to determine if a browser has been served a transition page recently e.g. last 48h. If so we redirect immediately, otherwise a transition page is served.
