### ISSUE TITLE
Apply lint to pre-commit hooks

### ISSUE THREAD

**Issue by kylerwsm** [opengovsg/GoGovSG#183]
**Is your feature request related to a problem? Please describe.**
While it is good that our code push now fails on lint errors, it is still possible to commit and push badly formatted code (formatting fixes need not be committed before the code can be pushed). While badly formatted code will be caught by our CI, it would be better if we have in-development measures as well.

**Describe the solution you'd like**
A pre-commit hook with lint-staged may be the ideal solution for this problem. This ensures that all of our commits are properly formatted and structured, and makes dedicated commits to fix stylings redundant. However, an obvious drawback will be additional delays when commit code changes.

**Describe alternatives you've considered**
I am open to hear alternative solutions!

**Comment by LoneRifle** [comment]
The pre-commit linting wouldn't have much delay since lint-staged can target only the files that are being committed. Given that CI is already doing the linting too, this would also mean that we can generally avoid linting the entire codebase pre-push, and get pre-push to do something like, say, commitlinting.
