### ISSUE TITLE
E2E test for drawer functionality fails on local machine

### ISSUE THREAD

**Issue by halfwhole** [opengovsg/GoGovSG#2003]
**Describe the bug**

Run `npx testcafe chrome ./test/end-to-end/DrawerLogin.test.ts -t "Drawer functionality test for url."` locally. It fails right at the end of the test with the following message:

```
 Drawer Page
 ✖ Drawer functionality test for url.

   1) A JavaScript error occurred on "https://github.com/".
      Repeat test actions in the browser and check the console for errors.
      To ignore client-side JavaScript errors, enable the "--skip-js-errors" CLI option, or set the "skipJsErrors"
      configuration file property to "true".
      If the website only throws this error when you test it with TestCafe, please create a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".
      
      JavaScript error details:
      Error: Cannot read property 'href' of null
          at t._error (http://192.168.68.54:60708/hammerhead.js:12:29048)
          at value (http://192.168.68.54:60708/hammerhead.js:12:30415)
          at s (https://github.githubassets.com/assets/behaviors-6ddb62eafb65.js:133:71001)
          at t (https://github.githubassets.com/assets/behaviors-6ddb62eafb65.js:133:72760)

      Browser: Chrome 105.0.0.0 / macOS 10.15.7
```

This is a bit strange because the same E2E test run by our actions don't fail like this.

**Expected behavior**

The test should pass.

**Additional context**

I just tried changing the target long URL from `github.com` to `example.com`, and the test passes locally. Perhaps we might just want to make that change, but also I'm not exactly sure why the above error occurs at all

**Comment by developerdenesh** [comment]
The issue seems to be coming from the underlying hammerjs library that's being used. The javascript error is exactly as described above in the devtools console as well: 

<img width="633" alt="Screenshot 2022-10-10 at 9 14 00 AM" src="https://user-images.githubusercontent.com/34817364/194788390-54ffb229-7062-479d-95e3-248b972db7d9.png">

An alternative would be to pass the --skip-js-errors flag into the testing script `npx testcafe chrome ./test/end-to-end/DrawerLogin.test.ts -t "Drawer functionality test for url." --skip-js-errors`, although this may prove dangerous because all other forms of Javascript errors will be ignored as well

**Comment by halfwhole** [comment]
Agree that it sounds dangerous to skip the errors for the sake of passing one test! What's curious is that the above error is both website-dependent and machine-dependent - why exactly that is in relation to testcafe/its underlying libraries appears to be a bit of a mystery :(

Have closed the issue through the accompanying PR as a quick fix, but would be happy to hear if you have any insights as to the cause of the issue!
