### ISSUE TITLE
CSP errors when accessing shortlinks with a trailing slash

### ISSUE THREAD

**Issue by yong-jie** [opengovsg/GoGovSG#427]
**Describe the bug**
CSP errors when accessing shortlinks with a trailing slash

**To Reproduce**
1. Create a link
2. Access the short url with a trailing slash
3. See error

**Expected behavior**
Transition page should be served with no problems

**Screenshots**
![image](https://user-images.githubusercontent.com/16982839/90399857-37118000-e0ce-11ea-8a00-c3d2a74519f7.png)

**Comment by LoneRifle** [comment]
Those aren't CSP errors _per se_. 

What's happening is that the transition page is trying to load resources from a path _relative to the current page:_
![image](https://user-images.githubusercontent.com/10572368/90579774-991ad400-e1f9-11ea-8cdc-b0887077894e.png)

Note the highlighted URL and ensuing 302. This results in the CSP errors in the console: for good reason, we refuse loading the long URL as an image/stylesheet/etc.

This issue should be fixed by fixing the paths in the transition page to point to the _site root_.
