### ISSUE TITLE
Login credentials for contributors

### ISSUE THREAD

**Issue by reiallenramos** [opengovsg/GoGovSG#46]
**Is your feature request related to a problem? Please describe.**
I got the app to work but can't look around further without login credentials.

**Describe the solution you'd like**
A task to migrate admin credentials to the database.

**Describe alternatives you've considered**
Maybe it's documented somewhere and I just missed it.

**Comment by liangyuanruo** [comment]
Hi @reiallenramos ,

You can login by setting the `VALID_EMAIL_GLOB_EXPRESSION` environment variable to e.g. `reiallenramos@gmail.com` and you should be able to log in with an emailed one-time password.

If you need to whitelist your work organisation, you can use `*@your-organisation.com`.

**Comment by reiallenramos** [comment]
@liangyuanruo  thanks. Still waiting for the OTP to be sent to my email. Here are the steps I took:
- set environment variable `VALID_EMAIL_GLOB_EXPRESSION` to my email address
- start the app via `npm run dev`

Did I miss anything?

**Comment by yong-jie** [comment]
When running locally, note that we use node-mailer-direct-transport, meaning your server attempts to send the email directly from your computer instead of through a service like Amazon's SES. 

What this means is that there's a possibility that your email provider (e.g. Gmail) might not trust your IP address, and could either block the email, or send it to your spam folder.

To mitigate this problem, when running locally, your one-time password (OTP) is always set to `111111`. So even if you dont manage to send/receive the email successfully, you can still log in via the default password.

**Comment by reiallenramos** [comment]
@yong-jie thanks man, I got it to work by setting `- VALID_EMAIL_GLOB_EXPRESSION=*` in `docker-compose.yml` and used the default OTP.

I might have found a UI bug and will submit a PR in few. Regards.
